version: '3.8'

services:
  backend:
    build:
      context: ./trade_journal_backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./trade_journal_backend/.env
    volumes:
      - ./trade_journal_backend:/app
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./trade_journal_frontend/trade-journal
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./trade_journal_frontend/trade-journal/.env
    volumes:
      - ./trade_journal_frontend/trade-journal:/app
    stdin_open: true
    restart: always

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: