version: "3.9"

services:
  trade-journal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true